#!/usr/bin/env php
<?php

/*\
 * 
 * This file is part of Copycode.
 *
 * (c) Francesco Bianco <bianco@javanile.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 * 
\*/

//
if (file_exists($a = __DIR__.'/../../autoload.php')) 
{
    require_once $a;
} 

//
else if (file_exists($a = __DIR__.'/vendor/autoload.php'))
{
    require_once $a;
}

//
else 
{
    require_once __DIR__.'/src/Javanile/Copycode/Copycode.php';
}

//
global $argv;

//
use Javanile\Copycode\Copycode;

//
$app = new Copycode();

//
$app->cli($argv);